<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>Tweakwell.Elevated</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishTrimmed>false</PublishTrimmed>
    <AssemblyName>Tweakwell.Elevated</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management" Version="9.0.8" />
    <ProjectReference Include="..\Tweakwell.Core\Tweakwell.Core.csproj" />
  </ItemGroup>
</Project>
